name: mllm_refusal
channels:
  - pytorch
  - defaults
  - anaconda
dependencies:
  - python=3.10
  - cudatoolkit
  - pip
  - pip:
    - torchvision==0.17.2
    - huggingface-hub
    - matplotlib==3.7.0
    - psutil==5.9.4
    - iopath
    - pyyaml==6.0
    - regex==2022.10.31
    - tokenizers
    - tqdm==4.64.1
    - transformers==4.37.2
    - timm==0.6.13
    - webdataset==0.2.48
    - omegaconf==2.3.0
    - opencv-python==4.7.0.72
    - decord==0.6.0
    - peft==0.2.0
    - sentence-transformers
    - accelerate==0.21.0
    - bitsandbytes
    - scikit-image
    - visual-genome
    - contexttimer
    - diffusers<=0.16.0
    - einops==0.6.1
    - fairscale==0.4.4
    - ftfy
    - ipython
    - opendatasets
    - packaging
    - plotly
    - pre-commit
    - pycocoevalcap
    - pycocotools
    - python-magic
    - sentencepiece
    - spacy
    - streamlit
    - wheel
    - soundfile
    - moviepy
    - nltk
    - easydict==1.9
    - pyyaml_env_tag==0.1
    - open3d
    - h5py
    - aiohttp
    - aiosignal
    - async-timeout
    - datasets
    - dill
    - et-xmlfile
    - frozenlist
    - multidict
    - multiprocess
    - openpyxl
    - protobuf
    - pyarrow
    - seaborn
    - xxhash
    - yarl
    - pandas
    - shortuuid
    - pydantic
    - scikit-learn==1.2.2
    - requests
    - httpx==0.24.0
    - uvicorn
    - fastapi
    - einops-exts==0.0.4
    - deepspeed==0.12.6
    - tiktoken
    - transformers_stream_generator==0.0.4
    - scipy
    - pillow
    - tensorboard
    - wandb
    - torchaudio==2.2.2