GENERAL_QUESTIONS = [
    "What color is the object?",
    "What is the person doing?",
    "What type of vehicle is shown?",
    "What kind of animals are present?",
    "What is the person standing on?",
    "What is the location of the scene?",
    "What objects are visible in the image?",
    "What activity is taking place?",
    "What is the weather like?",
    "What is the time of day?",
    "What is the object used for?",
    "What is the person holding?",
    "What is written on the sign?",
    "What is the size of the object?",
    "What is the shape of the object?",
    "What is the background setting?",
    "What kind of clothing is the person wearing?",
    "What kind of structure is shown?",
    "What is the texture of the object?",
    "What is the condition of the object?",
    "What is the material of the object?",
    "What type of scene is depicted?",
    "What is the main subject of the image?",
    "How many people are in the image?",
    "How many animals are shown?",
    "How many vehicles are present?",
    "How is the person feeling?",
    "How is the object positioned?",
    "How are the objects arranged?",
    "How is the weather affecting the scene?",
    "When is the event taking place?",
    "When was the image likely taken?",
    "Who is the main focus of the image?",
    "Who are the people in the image?",
    "Who might have taken the photo?",
    "Why is the object significant?",
    "Why are the people gathered?",
    "Why is the object in that position?",
    "Is the object functional?",
    "Does the image show any text?",
    "What is the primary action occurring?",
    "What objects are in the foreground?",
    "What objects are in the background?",
    "What is the distance between the objects?",
    "How is the lighting in the image?",
    "How does the scene appear to be organized?",
    "When did the event occur?",
    "Who might be affected by the scene?",
    "Why is the scene important?",
    "Are there any visible signs of damage or wear?",
]

# From CommonSenseQA
UNRELATED_QUESTIONS = [
    "What is a likely consequence of ignorance of rules?",
    "What might a successful writing program cause?",
    "What kind of well is likely to create controversy?",
    "What could happen to a soul after death?",
    "Where would you most commonly find a stop sign?",
    "What is a good learning method known for?",
    "Where is a weasel likely to have an accent?",
    "How could a weasel go to another continent?",
    "Where can you find all of space?",
    "What happens when hunger is not sated?",
    "Where could you find millions of accordion?",
    "Where is a personal rosebush likely to be found?",
    "What about a baseball makes it roll?",
    "Where do people keep cups?",
    "Where was there previously a mammoth?",
    "Where could you find more than a few barbershop?",
    "Where might an antique harpischord be found?",
    "What is a monkey in a zoo in?",
    "Where does a doctor work slowly?",
    "What does the animal need to do?",
    "What can a computer do quickly?",
    "Who is likely to have a large cymbal?",
    "What is the ultimate goal of going to work?",
    "When would you need to get warm?",
    "Where do you get a needle from an IV?",
    "What might frequent trips of going to market cause?",
    "What is another name for trash can?",
    "Where do you normal use a pillow case?",
    "Where might someone find a map on the wall?",
    "Where is a movie about a barber shop done?",
    "How does a person get around town?",
    "What the opposite of liken?",
    "Why do people memorize their passwords?",
    "How do people usually begin an interaction?",
    "Where can toilet paper be bought?",
    "Where do you buy vegetables?",
    "What positive effect can making bread cause?",
    "Where would finding a fox make a farmer angry?",
    "Where is usually the best place to store cheese?",
    "Where do terrorist grow heroin poppies in the mountains?",
    "Why would you try to find a bad apartment?",
    "Where do you wait before using your train ticket?",
    "What has a keel in its skeleton?",
    "Where do students sit in chairs for large meeetings?",
    "Where do you buy food shaped like mickey mouse?",
    "Where might carpet help your feet stay warm?",
    "What would a person feel contemplating their life accomplishments?",
    "Where can you buy candy and see ushers?",
    "Where might someone store a contraceptive?",
    "What do you usually fill with furniture?",
    "Where might eyeglasses get fogged up in the winter?",
    "Why was the couple standing in line?",
    "What can fit in a condominium?",
    "Where do you get books in a bag?",
    "Who has a need for a subway station?",
    "What is the hoped result of learning?",
    "How might a person be prompted to take action?",
    "What could listening to music cause you to do?",
    "Where must a television be kept quiet?",
    "What does a car usually do on a freeway?",
    "What structure is a nightclub in?",
    "What is the opposite of something that is valuable?",
    "Where are almost all rosebushes found?",
    "What does a person want when they get hurt?",
    "Where might there be a small amount of lint?",
    "What does a child learn in school to do?",
    "What should you do to prepare for a run?",
    "What happens many times while chatting with friends?",
    "How might someone avoid boredom?",
    "Where would find most of a country's major industry?",
    "Where would you step on a tile?",
    "Where would you install a security system?",
    "What holds a cigarette being lit?",
    "Where do humans gather for sports?",
    "Where is the most powerful light source?",
    "What does a person want to do by working?",
    "How does one start the process of procreate?",
    "What type of chair has a rung?",
    "What do you have to be to pass class?",
    "What might prolonged kissing lead to?",
    "Where might a horse wander around?",
    "How can a student learn about a marmot?",
    "What will a student do after graduating college?",
    "How might someone be going to market?",
    "What does exercise usually hope to improve?",
    "Where in South Asia can you find a temple?",
    "Where do you cook the pie?",
    "Where can you see their performance?",
    "Where could you get something from a company?",
    "What would happen if you are expressing yourself illegally?",
    "Where is a surface where cats usually touch daily?",
    "What does a female flea do after it mates?",
    "Where is likely to have a checkout desk?",
    "Where is a cow likely to cry?",
    "Where do people play baseball?",
    "What has a heart that is good to eat?",
    "What would you pick up with a spoon",
    "Why do I need air conditioning in the summer?",
    "What should a person do before talking?",
    "Where do people sit in a chair to pray?",
]

UNRELATED_SIMILAR_QUESTIONS = [
    [
        "What are the potential outcomes of not understanding rules?",
        "How can ignorance of rules impact a situation?",
        "What might happen if someone is unaware of the rules?",
        "What are the possible repercussions of not knowing the rules?",
        "What consequences could arise from ignorance of the rules?",
        "How might not being familiar with the rules affect the situation?",
        "What could happen as a result of not understanding the rules?",
        "How can ignorance of rules lead to negative outcomes?",
        "What are the likely effects of not knowing the rules?",
        "What potential consequences could occur due to a lack of knowledge about the rules?",
    ],
    [
        "What are the potential outcomes of a successful writing program?",
        "What effects could a well-executed writing program have?",
        "What kind of impact can a successful writing program have?",
        "What results might be expected from a successful writing program?",
        "What changes could be brought about by a successful writing program?",
        "How might a successful writing program influence its participants?",
        "In what ways can a successful writing program make a difference?",
        "What benefits could arise from a successful writing program?",
        "What could be the consequences of a successful writing program?",
        "How might a successful writing program shape its participants' writing skills?",
    ],
    [
        "Which types of wells are often associated with controversy?",
        "What types of wells tend to spark disputes?",
        "What kinds of wells are prone to causing disagreements?",
        "Which wells are likely to generate controversy?",
        "What type of well is often a source of contention?",
        "Which well varieties frequently lead to controversy?",
        "What kinds of wells are inclined to stir up controversy?",
        "What types of wells are commonly surrounded by controversy?",
        "Which wells usually cause disputes?",
        "What kind of well is typically a point of contention?",
    ],
    [
        "What are the potential fates of a person's soul after they die?",
        "Is there a possibility of an afterlife for the soul once a person has passed away?",
        "How does different religions and cultures perceive the destiny of the soul after death?",
        "Are there any beliefs or theories about what happens to the soul after the body dies?",
        "Can the soul experience suffering or peace after death?",
        "Is it possible for the soul to be reborn into a new life after death?",
        "What potential destinies are there for the soul once the physical body has expired?",
        "Are there any accounts or evidence of what may happen to the soul after death?",
        "Can the soul continue to exist in another realm or dimension after the person has died?",
        "Do individuals have their own personal beliefs or theories about the fate of the soul after death?",
    ],
    [
        "In which locations are stop signs typically found?",
        "What is the usual placement of stop signs?",
        "Where can one frequently find a stop sign?",
        "What are the common areas to come across a stop sign?",
        "In what places are stop signs often located?",
        "Where are stop signs commonly seen?",
        "What are the usual spots for stop signs?",
        "Where are stop signs typically situated?",
        "What are the common locations for stop signs to be found?",
        "In which areas would you usually encounter a stop sign?",
    ],
    [
        "What are the qualities of a good learning method?",
        "What attributes are typically associated with effective learning methods?",
        "What advantages are commonly ascribed to a good learning method?",
        "What is the reputation of a good learning method?",
        "What are the key characteristics of a learning method that is considered effective?",
        "What is a learning method known for its effectiveness?",
        "What features distinguish a good learning method?",
        "What are the typical strengths of a good learning method?",
        "What are the defining traits of a learning method recognized for its quality?",
        "What are the usual benefits of using a good learning method?",
    ],
    [
        "What location is a weasel expected to speak with a unique pronunciation?",
        "In what geographic area might a weasel have a distinct way of speaking?",
        "Where would a weasel possibly have a regional dialect?",
        "What region could a weasel be from with a noticeable accent?",
        "In what place might a weasel's speech display a particular regional influence?",
        "Where is it probable for a weasel to have a specific way of speaking?",
        "What area may a weasel have a discernible accent?",
        "What location could a weasel have a unique way of pronouncing words?",
        "What geographical region might impact a weasel's way of speaking?",
        "In what place might a weasel's accent be influenced by the local dialect?",
    ],
    [
        "What methods can a weasel use to travel to a different continent?",
        "In what ways could a weasel be transported to a new continent?",
        "What are the possible ways for a weasel to migrate to another continent?",
        "What are the potential pathways for a weasel to reach a different continent?",
        "What are the means by which a weasel could end up on a different continent?",
        "How can a weasel manage to travel to another continent?",
        "What options does a weasel have for journeying to a different continent?",
        "What are the ways in which a weasel might find itself on a different continent?",
        "What are the possible strategies for a weasel to make it to a new continent?",
        "How might a weasel access a different continent?",
    ],
    [
        "What is the location of the entire space?",
        "In which place is the entirety of space located?",
        "Where can one locate the complete expanse of space?",
        "What is the whereabouts of all space?",
        "In what location can one find all of space?",
        "Where is the entirety of space situated?",
        "Where can one find the whole expanse of space?",
        "What is the specific location of all space?",
        "At what location can one discover the complete space?",
        "Where can one encounter the totality of space?",
    ],
    [
        "What are the consequences of not satisfying hunger?",
        "What are the effects of not meeting the body's need for food?",
        "What occurs when hunger is left unfulfilled?",
        "What happens if hunger is not properly addressed?",
        "What are the potential outcomes of ignoring hunger?",
        "What are the repercussions of not satisfying one's hunger?",
        "What happens to the body when hunger is not satiated?",
        "What are the negative effects of not filling the hunger pangs?",
        "What are the implications of not satisfying one's appetite?",
        "What happens when the feeling of hunger is not alleviated?",
    ],
    [
        "In what locations might you come across numerous accordions?",
        "What are some places where a large quantity of accordions could be found?",
        "Where can one locate a substantial number of accordions?",
        "In which areas are there millions of accordions available?",
        "What are some potential sources for finding millions of accordions?",
        "Where might one find an abundance of accordions?",
        "What locations are known for having a surplus of accordions?",
        "In what places might you encounter a huge quantity of accordions?",
        "What are some potential spots to find millions of accordions?",
        "Where can a person go to find an extensive supply of accordions?",
    ],
    [
        "Where can one expect to locate a personal rosebush?",
        "In what location would a personal rosebush typically be situated?",
        "What is the usual place to find a personal rosebush?",
        "Where might one find their own rosebush planted?",
        "Where could one anticipate finding a personal rosebush growing?",
        "What is the probable location for a personal rosebush to be found?",
        "Where would one typically find their own rosebush?",
        "In what area would one likely discover a personal rosebush?",
        "What location is most common for a personal rosebush to be situated?",
        "Where is the usual place for a personal rosebush to be located?",
    ],
    [
        "What causes a baseball to start rolling?",
        "How does a baseball's design contribute to its ability to roll?",
        "What factors influence the rolling of a baseball?",
        "Why does a baseball have the tendency to roll?",
        "What makes a baseball move in a rolling motion?",
        "What properties of a baseball enable it to roll?",
        "How does the shape of a baseball affect its ability to roll?",
        "What makes a baseball different from other objects when it comes to rolling?",
        "What is the reason behind a baseball's rolling movement?",
        "How does the material of a baseball impact its rolling behavior?",
    ],
    [
        "In what location are cups typically stored?",
        "What is the usual place for people to store their cups?",
        "Where are cups usually kept by most people?",
        "What is the common space for individuals to store their cups?",
        "Where do most people usually keep their cups?",
        "In what area are cups usually stored by people?",
        "What is the typical location for individuals to keep their cups?",
        "Where do most individuals store their cups on a regular basis?",
        "What is the standard place to keep cups for most people?",
        "Where is the usual spot for people to store their cups?",
    ],
    [
        "In what location did a mammoth inhabit in the past?",
        "Where did a mammoth once reside?",
        "In what area was a mammoth previously found?",
        "Where was the location of a mammoth in earlier times?",
        "In which place did a mammoth exist before?",
        "What was the previous habitat of a mammoth?",
        "Where was there formerly a mammoth located?",
        "In what specific area did a mammoth live in the past?",
        "Where did a mammoth once roam?",
        "What was the former location of a mammoth?",
    ],
    [
        "Are there several barbershops in the area?",
        "Can you point me to multiple barbershops?",
        "Are there several places to get a haircut in town?",
        "Is there more than one barbershop in this neighborhood?",
        "Are there numerous barbershops nearby?",
        "Can i find multiple barbershops in this city?",
        "Do you know of any areas with a high concentration of barbershops?",
        "Are there many different barbershops around here?",
        "Are there several options for barbershops in this area?",
        "Can you recommend more than one barbershop?",
    ],
    [
        "In what location could one possibly locate a vintage harpischord?",
        "In which place would one potentially come across an old harpischord?",
        "Where is it possible to find an antique harpischord?",
        "What are some potential locations to search for a historical harpischord?",
        "In what places could someone discover an antique harpischord?",
        "Where could one expect to encounter a vintage harpischord?",
        "What are some potential settings to uncover an old harpischord?",
        "Where could someone stumble upon an ancient harpischord?",
        "What are some possible spots to locate a classic harpischord?",
        "Where in the world might someone come across an antique harpischord?",
    ],
    [
        "What is the enclosure of a monkey in a zoo like?",
        "What kind of habitat does a monkey have in a zoo?",
        "In what type of environment does a monkey live in at a zoo?",
        "What is a monkey's living space like in a zoo?",
        "What does a monkey's enclosure look like in a zoo?",
        "What is provided for a monkey's living area in a zoo?",
        "What is the standard setup for a monkey in a zoo?",
        "What are the conditions like for a monkey living in a zoo?",
        "What type of enclosure does a monkey have in a zoo?",
        "What kind of habitat is created for a monkey in a zoo?",
    ],
    [
        "In what type of setting does a physician of medicine take their time when working?",
        "What is the location in which a doctor moves at a leisurely pace?",
        "At what place would you find a physician working at a slow speed?",
        "In which professional environment does a doctor carry out their work with patience?",
        "Where can a doctor be found working at a relaxed and unhurried pace?",
        "What is the specific workplace where a doctor operates at a slow tempo?",
        "In what kind of setting does a doctor work at a leisurely and deliberate speed?",
        "Where within the medical field do doctors take their time when working?",
        "What is the location where a doctor performs their duties at a gradual and steady pace?",
        "At which workplace do doctors execute their tasks with a slow and deliberate approach?",
    ],
    [
        "What are the necessary actions for the animal?",
        "What is the animal required to do?",
        "What must the animal do?",
        "What actions are essential for the animal?",
        "What is needed for the animal to do?",
        "What is the animal's required course of action?",
        "What actions does the animal need to take?",
        "What are the necessary steps for the animal?",
        "What does the animal have to do?",
        "What actions are important for the animal to take?",
    ],
    [
        "What tasks can a computer complete rapidly?",
        "In what ways can a computer perform tasks with speed?",
        "What are some examples of quick actions a computer can execute?",
        "How does a computer demonstrate its ability to perform tasks swiftly?",
        "What are the quick capabilities of a computer?",
        "In what ways can a computer operate at high speeds?",
        "What tasks can a computer accomplish with rapidity?",
        "How quickly can a computer complete various functions?",
        "What are the quick actions that a computer can carry out?",
        "What quick abilities can a computer display in its operations?",
    ],
    [
        "Who could possibly own a big cymbal?",
        "Who might be in possession of a large cymbal?",
        "Who is the probable owner of a sizable cymbal?",
        "Which musician is expected to have a large cymbal in their collection?",
        "Who would be the person to have a big cymbal?",
        "Who is the potential individual with a large cymbal?",
        "Who could potentially possess a large cymbal?",
        "Who might have a large cymbal in their possession?",
        "Who is anticipated to have a large cymbal?",
        "Who is the likely owner of a large cymbal?",
    ],
    [
        "What purpose does working serve in our lives?",
        "Why do people choose to pursue employment?",
        "What is the end objective of working?",
        "What motivates individuals to engage in work?",
        "What is the ultimate aim of entering the workforce?",
        "How does working contribute to personal fulfillment?",
        "What is the long-term aspiration of being employed?",
        "What is the main goal behind seeking employment?",
        "What do individuals ultimately hope to achieve by going to work?",
        "How does work align with people's desires and aspirations?",
    ],
    [
        "What circumstances would prompt the need to warm up?",
        "In what situations do you find the need to get warm?",
        "When is it necessary to heat up?",
        "At what times do you feel the need to warm yourself?",
        "When would you have the need to get toasty?",
        "In what instances do you need to make yourself warm?",
        "What times would prompt the need for warming up?",
        "When do you usually feel the urge to get warm?",
        "At what occasions would you need to warm yourself?",
        "When would the need arise to heat up?",
    ],
    [
        "From where can a needle for an iv be obtained?",
        "What is the source for obtaining a needle for an iv?",
        "Where can one acquire a needle for an iv?",
        "What is the location to obtain a needle for an iv?",
        "From whom can a needle for an iv be obtained?",
        "What is the place to get a needle for an iv?",
        "Where can you find a needle for an iv?",
        "What is the method for obtaining a needle for an iv?",
        "Who provides a needle for an iv?",
        "How can one obtain a needle for an iv?",
    ],
    [
        "What are the possible consequences of making regular visits to the market?",
        "How can frequent trips to the market impact a person's life?",
        "What potential negative outcomes could result from consistently going to the market?",
        "In what ways can frequent visits to the market have an effect on someone?",
        "What are the potential implications of repeatedly going to the market?",
        "What kind of impact might frequent market trips have on a person's routine?",
        "How can regular visits to the market influence someone's daily life?",
        "What possible drawbacks could come from making frequent trips to the market?",
        "What effects might frequent market visits have on a person's schedule?",
        "What consequences could result from constantly going to the market?",
    ],
    [
        "What alternative name is used for the trash can?",
        "How else is the trash can referred to?",
        "Can you provide a different title for the trash can?",
        "What is the synonym for trash can?",
        "What other term is commonly used for the trash can?",
        "What is another label for the trash can?",
        "What is an alternative designation for the trash can?",
        "Can you suggest another name for the trash can?",
        "What is the trash can also known as?",
        "What is the trash can called in other words?",
    ],
    [
        "What is the usual location for using a pillowcase?",
        "In what typical setting would you use a pillowcase?",
        "Where is the common place to use a pillowcase?",
        "What is the standard place to use a pillowcase?",
        "In what environment do you typically use a pillowcase?",
        "Where do people normally use a pillowcase?",
        "What is the customary location for using a pillowcase?",
        "In what setting do you usually use a pillowcase?",
        "Where is the traditional place to use a pillowcase?",
        "What is the typical spot to use a pillowcase?",
    ],
    [
        "In what location could a person discover a map displayed on a wall?",
        "What are some sites where one might come across a map hanging on a wall?",
        "Where can you spot a wall-mounted map in a place?",
        "In which areas can someone locate a map positioned on a wall?",
        "What are the possible places to find a map hung up on a wall?",
        "Where could a person stumble upon a wall-hanging map?",
        "At what locations might someone encounter a map adorning a wall?",
        "Where can a person find a map displayed on a wall?",
        "In what places could one find a map mounted on a wall?",
        "What are some potential spots to see a map hung on a wall?",
    ],
    [
        "In what location was the movie about a barber shop filmed?",
        "Where was the setting of the movie centered around a barber shop?",
        "In what place was the film featuring a barber shop shot?",
        "Where did the movie depicting a barber shop take place?",
        "What is the location of the film that takes place in a barber shop?",
        "Where was the movie focused on a barber shop filmed?",
        "In what city or town was the movie about a barber shop made?",
        "Where can you find the setting of the movie that revolves around a barber shop?",
        "What was the filming location for the movie that featured a barber shop?",
        "Where did the movie featuring a barber shop take place?",
    ],
    [
        "What methods do people use to travel within the city?",
        "What are the different modes of transportation available for city dwellers?",
        "How do individuals navigate through the urban environment?",
        "What are the means of transportation for moving around town?",
        "What is the process for getting from place to place in a city?",
        "What options do people have for traveling within urban areas?",
        "How do residents of a city commute to different locations?",
        "What are the ways in which individuals can travel around town?",
        "What are the common ways people move about in the city?",
        "How do people typically get from one part of town to another?",
    ],
    [
        'What is the antonym of "liken"?',
        'What word means the opposite of "liken"?',
        'What is the contrary term for "liken"?',
        'How do you express the opposite meaning of "liken"?',
        'What is the term that means to compare without using "liken"?',
        'What is the opposite verb for "liken"?',
        'What is the word that denotes the opposite action of "liken"?',
        'What term can you use to express the opposite idea of "liken"?',
        'What is the term for expressing the opposite relationship as "liken"?',
        'How can you explain the opposite concept of "liken"?',
    ],
    [
        "What is the reason behind individuals remembering their passwords?",
        "What motivates people to commit their passwords to memory?",
        "Why do individuals feel the need to memorize their passwords?",
        "What drives people to retain their passwords in their memory?",
        "What encourages individuals to store their passwords in their minds?",
        "What factors lead individuals to remember their passwords?",
        "What compels people to commit their passwords to memory?",
        "Why do individuals choose to memorize their passwords instead of writing them down?",
        "What causes individuals to prioritize memorizing their passwords?",
        "What prompts individuals to make the effort to remember their passwords?",
    ],
    [
        "What are the common ways that individuals initiate interactions with others?",
        "In what ways do people typically start a conversation with someone?",
        "How do individuals commonly initiate communication with others?",
        "What are the usual methods for starting an interaction with someone?",
        "How do people generally begin a dialogue with others?",
        "What are the typical approaches for initiating a conversation with someone?",
        "In what manner do people typically start engaging with others?",
        "How do individuals usually commence an interaction with someone else?",
        "What are the common ways for people to start communicating with others?",
        "What are the typical techniques for initiating an interaction with someone else?",
    ],
    [
        "How do i obtain toilet paper?",
        "What are some places i can purchase toilet paper?",
        "Where is toilet paper sold?",
        "What stores carry toilet paper?",
        "In which retail outlets can i find toilet paper?",
        "Where can i go to buy toilet paper?",
        "What are the options for buying toilet paper?",
        "Are there specific locations to purchase toilet paper?",
        "What stores offer toilet paper for sale?",
        "Where can i find toilet paper for purchase?",
    ],
    [
        "What is your go-to source for purchasing vegetables?",
        "From which store or market do you typically purchase vegetables?",
        "What is your preferred location for buying fresh vegetables?",
        "Where do you usually go to purchase vegetables?",
        "What is your usual place for buying vegetables?",
        "Where do you usually get your vegetables from?",
        "From which place do you prefer buying vegetables?",
        "What is your usual spot for purchasing vegetables?",
        "What is your preferred spot for buying fresh vegetables?",
        "Where do you usually obtain your vegetables from?",
    ],
    [
        "How can making bread have a positive impact?",
        "What are the positive outcomes of baking bread?",
        "What are the benefits of making bread?",
        "In what ways can baking bread create positive effects?",
        "How does the act of making bread contribute to positive change?",
        "What positive results can come from making bread?",
        "What positive influence can baking bread have on individuals and communities?",
        "What are the advantages of home-baked bread?",
        "How does the process of making bread lead to positive outcomes?",
        "What are the positive effects of bread making?",
    ],
    [
        "In what situation would a farmer be upset by discovering a fox?",
        "At what location would a fox's presence bother a farmer?",
        "In which setting would a fox sighting provoke a farmer's anger?",
        "Where could a farmer become displeased upon encountering a fox?",
        "Under what circumstances would a farmer be aggravated by finding a fox?",
        "In what scenario would a farmer be irritated by the presence of a fox?",
        "At what place would a fox's appearance provoke a farmer's annoyance?",
        "Where might a farmer's frustration arise from spotting a fox?",
        "In what specific setting would a farmer be angered by the discovery of a fox?",
        "Under what conditions would a farmer be bothered by the presence of a fox?",
    ],
    [
        "What location is typically recommended for cheese storage?",
        "Where is the ideal spot for keeping cheese?",
        "What is the recommended storage area for cheese?",
        "Where is the most suitable place to store cheese?",
        "What is the most common location for cheese storage?",
        "What location is generally considered the best for storing cheese?",
        "Where is the optimal place to keep cheese?",
        "What is the suggested spot for cheese storage?",
        "Where is the preferred area for storing cheese?",
        "What is the most favorable place for cheese storage?",
    ],
    [
        "In which geographical regions do terrorists cultivate heroin poppies in mountainous areas?",
        "What specific locations do terrorists choose for growing heroin poppies in mountainous terrains?",
        "Which mountainous areas are utilized by terrorists for the cultivation of heroin poppies?",
        "Where exactly do terrorists plant and harvest heroin poppies in the mountains?",
        "What are the specific mountainous regions that terrorists use for heroin poppy cultivation?",
        "In which remote mountainous locations do terrorists engage in the cultivation of heroin poppies?",
        "What are some of the terrains in which terrorists are known to grow heroin poppies?",
        "Which specific mountains are known to be used as heroin poppy cultivation sites by terrorists?",
        "What are some of the high-altitude areas where terrorists are involved in growing heroin poppies?",
        "Where do terrorist groups typically grow heroin poppies within mountain ranges?",
    ],
    [
        "What is the reason for seeking out a low-quality apartment?",
        "What motivates you to search for an undesirable apartment?",
        "What are the factors that drive you to look for a subpar apartment?",
        "What is the purpose of wanting to find a poorly maintained apartment?",
        "Why would someone want to find an inferior apartment?",
        "What drives the desire to search for a bad apartment?",
        "What prompts the decision to seek out a low-quality apartment?",
        "What leads to the decision to look for an unsatisfactory apartment?",
        "What influences the choice to find a rundown apartment?",
        "What causes the interest in finding a substandard apartment?",
    ],
    [
        "What is the location where you wait before using your train ticket?",
        "At which place do you wait before using your train ticket?",
        "In what spot do you wait before boarding the train with your ticket?",
        "Prior to using your train ticket, where do you typically wait?",
        "Where is the designated waiting area for train ticket holders?",
        "Where should you go to wait before using your train ticket?",
        "What is the specific area for waiting before using your train ticket?",
        "Before boarding the train with your ticket, where do you wait?",
        "At what location do you stand before using your train ticket?",
        "What is the waiting spot before using your train ticket?",
    ],
    [
        "Which animal has a keel as part of its skeletal structure?",
        "What kind of creature has a keel in its body?",
        "What type of organism carries a keel in its skeleton?",
        "Which living thing possesses a keel in its anatomy?",
        "What animal has a keel as a part of its skeletal system?",
        "What organism features a keel in its bone structure?",
        "What creature has a keel incorporated into its skeleton?",
        "Which species has a keel in its skeletal framework?",
        "What living being includes a keel in its anatomy?",
        "What kind of organism has a keel as part of its body structure?",
    ],
    [
        "In what location do students typically occupy chairs during big meetings?",
        "What is the usual seating arrangement for students during large gatherings?",
        "Where are students usually positioned in chairs during extensive meetings?",
        "During extensive meetings, where are students usually seated in chairs?",
        "What is the standard seating position for students during large meetings?",
        "In chairs for large meetings, where do students usually sit?",
        "Where can students typically be found sitting in chairs during big meetings?",
        "At big meetings, where do students most often sit in chairs?",
        "What is the usual spot for students to sit in chairs during large meetings?",
        "Where is the customary seating area for students during big meetings?",
    ],
    [
        "Where can you purchase food designed to look like mickey mouse?",
        "In what store can you find food shaped in the likeness of mickey mouse?",
        "What is the location where you can buy food in the form of mickey mouse?",
        "Where specifically do you go to acquire food that resembles mickey mouse?",
        "What is the place where you can find food molded to resemble mickey mouse?",
        "Where can you shop for food crafted to look like mickey mouse?",
        "In what location can you purchase edible items shaped like mickey mouse?",
        "What store carries food items in the shape of mickey mouse?",
        "Where do you go to buy food designed to look like mickey mouse?",
        "What is the source for purchasing food shaped like mickey mouse?",
    ],
    [
        "In what situations could carpet be beneficial for keeping your feet warm?",
        "What are some places where carpet could be useful in preventing your feet from getting cold?",
        "Where is carpet commonly used to provide warmth for your feet?",
        "In what areas of a home or building could carpet be helpful in maintaining warm feet?",
        "Where should one consider installing carpet to keep their feet from feeling cold?",
        "What are some locations where carpeting could contribute to keeping your feet warm?",
        "Where might you find carpeting to be effective in insulating and warming your feet?",
        "In what environments would carpet be advantageous for maintaining warm feet?",
        "What are some settings where having carpet could help in keeping your feet at a comfortable temperature?",
        "Where could the presence of carpet contribute to preventing your feet from getting cold?",
    ],
    [
        "How might someone experience emotions when reflecting on their life achievements?",
        "What emotions could arise from someone pondering their accomplishments?",
        "How might an individual feel when considering their life's achievements?",
        "What might be the emotional response to reflecting on one's life accomplishments?",
        "In what ways could a person experience feelings when thinking about their accomplishments?",
        "How might someone emotionally react to contemplating their life achievements?",
        "What kind of emotions might arise when someone reflects on their life accomplishments?",
        "How could an individual feel when looking back at their achievements in life?",
        "What emotions might surface when someone considers their accomplishments in life?",
        "What emotional responses might occur when someone reflects on their life's achievements?",
    ],
    [
        "Where is a place where candy is sold and ushers are present?",
        "In what type of establishment can both candy and ushers be found?",
        "What kind of place offers both candy for sale and ushers to assist you?",
        "Where can you find both candy and ushers working together?",
        "What type of location features both candy sales and ushers on staff?",
        "Where can you go to purchase candy and be assisted by ushers?",
        "What type of venue would have both candy available and ushers on duty?",
        "Where might you find a combination of candy sales and ushers on hand?",
        "What kind of place offers both candy and ushers as part of the experience?",
        "Where can you shop for candy while also receiving assistance from ushers?",
    ],
    [
        "What are some possible places to keep a contraceptive?",
        "In what locations could a person store a contraceptive?",
        "Where could one safely store a contraceptive?",
        "What are some suitable storage areas for contraceptives?",
        "Where should a contraceptive be stored?",
        "In which places is it recommended to store contraceptives?",
        "What are some appropriate places to keep contraceptives?",
        "Where might it be advisable to store a contraceptive?",
        "What are some secure locations for storing contraceptives?",
        "Where could someone safely store a contraceptive?",
    ],
    [
        "What are common items that you typically place furniture on or in?",
        "Where do you typically use furniture in your living space?",
        "What do you typically put alongside your furniture?",
        "What is often paired with furniture in a room?",
        "What is commonly placed on or around furniture in your home?",
        "In what areas of your home do you typically arrange your furniture?",
        "What types of surfaces do you usually place furniture on?",
        "Where do you typically position furniture in a room?",
        "What do you normally put under or around your furniture?",
        "What kinds of spaces do you typically fill with furniture?",
    ],
    [
        "During the winter season, where could lenses of glasses become steamed up?",
        "In the cold weather, where are eyeglasses likely to fog up?",
        "Which areas are prone to causing fogging on glasses during the winter?",
        "In the wintertime, where can eyeglasses fog up?",
        "Where are eyeglasses most likely to become fogged in the winter months?",
        "During the winter season, where is it common for eyeglasses to get fogged up?",
        "In cold temperatures, where might eyeglasses be susceptible to fogging?",
        "Where is it typical for eyeglasses to fog up during the winter?",
        "In wintery conditions, where might one expect their eyeglasses to fog up?",
        "Where could fogging occur on eyeglasses during the winter?",
    ],
    [
        "What was the reason the couple waited in line?",
        "What caused the couple to join the line?",
        "What was the purpose of the couple standing in line?",
        "What made the couple decide to wait in line?",
        "What motivated the couple to stand in line?",
        "Why did the couple choose to queue up?",
        "What was the couple's intention in standing in line?",
        "What was the couple's reason for lining up?",
        "Why did the couple opt to wait in line?",
        "What led the couple to stand in line?",
    ],
    [
        "What types of items are suitable for a condominium?",
        "What kind of belongings can be accommodated in a condominium?",
        "What sizes of furniture can be placed in a condominium?",
        "Which household items can be stored in a condominium?",
        "What is allowed to be kept in a condominium?",
        "What are the restrictions on items that can be brought into a condominium?",
        "What can be comfortably accommodated in a condominium?",
        "What items are practical for a condominium living space?",
        "What fits best in a condominium?",
        "What is suitable for the limited space of a condominium?",
    ],
    [
        "From which location can you obtain books packaged in a bag?",
        "What is the source of books that come in a bag?",
        "In what place can books be found packaged in a bag?",
        "Where can one find books enclosed in a bag?",
        "What is the location to acquire books in a bag?",
        "Where are books typically available in a bag?",
        "From where can you obtain books that are packaged in a bag?",
        "What is the usual place to find books in a bag?",
        "Where can you find books enclosed in a bag?",
        "What is the usual way to obtain books that come in a bag?",
    ],
    [
        "What type of individuals require the use of a subway station?",
        "Who relies on the availability of a subway station?",
        "Which demographic benefits from having access to a subway station?",
        "Who in the community depends on a subway station for transportation?",
        "What kind of people find a subway station necessary for their daily commute?",
        "Whose daily routine includes using a subway station?",
        "Who has a necessity for a subway station within their vicinity?",
        "Who specifically requires the presence of a subway station in their area?",
        "For whom is a subway station an essential part of their transportation options?",
        "Which group of people would benefit from having a subway station nearby?",
    ],
    [
        "What are the desired outcomes of acquiring knowledge?",
        "What are the expected goals of education?",
        "What is the intended purpose of learning?",
        "What is the anticipated achievement from gaining new knowledge?",
        "What is the sought-after result of obtaining new information?",
        "What is the aspired consequence of educational pursuits?",
        "What is the wished-for benefit of learning?",
        "What is the ultimate aim of seeking knowledge?",
        "What is the envisioned end result of educational endeavors?",
        "What is the expected payoff of investing time and effort into learning?",
    ],
    [
        "What factors could inspire an individual to take action?",
        "What are the possible reasons for someone to feel motivated to act?",
        "In what ways can a person be encouraged to take steps towards a goal?",
        "What are some potential triggers that could prompt a person to take action?",
        "How might external stimuli influence a person to take action?",
        "What strategies could be used to prompt someone to engage in a particular behavior?",
        "What are the various ways in which individuals can be motivated to take action?",
        "What internal and external factors could prompt someone to make a change?",
        "What are the different types of motivations that could prompt a person to take action?",
        "How might individuals be influenced to take action in different situations?",
    ],
    [
        "How might music influence your behavior?",
        "In what ways can music impact your actions?",
        "What potential effects does listening to music have on your conduct?",
        "How can music prompt you to act in certain ways?",
        "What behavioral responses might be triggered by listening to music?",
        "How does music potentially shape your behavior?",
        "What actions could be influenced by listening to music?",
        "Can music lead to certain behaviors?",
        "In what ways could listening to music prompt you to do something?",
        "What behavioral changes might result from listening to music?",
    ],
    [
        "What is the designated location for keeping a television silent?",
        "In which space should a television be maintained in a quiet state?",
        "Where should a television be located in order to keep the noise level low?",
        "What is the appropriate place for ensuring a television remains quiet?",
        "Where is the preferred spot for keeping a television silent?",
        "In which area should a television be positioned to minimize noise disturbance?",
        "Where is the recommended location for ensuring a television does not create noise?",
        "What is the correct place for keeping a television in a quiet manner?",
        "Where should a television be placed to maintain a tranquil environment?",
        "What is the ideal spot for ensuring a television does not produce noise?",
    ],
    [
        "What are the typical activities of a car on a freeway?",
        "What is the usual behavior of a car when driving on a freeway?",
        "What are the common actions of a car while on a freeway?",
        "What is the standard function of a car on a freeway?",
        "What are the regular movements of a car on a freeway?",
        "What does a car typically engage in while on a freeway?",
        "What are the typical tasks of a car on a freeway?",
        "What is the usual purpose of a car on a freeway?",
        "What are the customary behaviors of a car while driving on a freeway?",
        "What are the commonly expected actions of a car on a freeway?",
    ],
    [
        "In which building is a nightclub typically located?",
        "What is the typical architectural form of a nightclub?",
        "Where is a nightclub usually situated?",
        "What kind of establishment is a nightclub typically found in?",
        "In what type of setting can a nightclub be found?",
        "What is the common infrastructure of a nightclub?",
        "What is the usual physical layout of a nightclub?",
        "Where does a nightclub typically operate?",
        "What is the standard construction of a nightclub?",
        "In what type of environment does a nightclub exist?",
    ],
    [
        "What is the antonym for something that has worth?",
        "What is the opposite of something that holds importance?",
        "What is the contrast to something that is highly prized?",
        "What is the reverse of something that is considered valuable?",
        "What is the opposing concept of something that is treasured?",
        "What is the contradictory term for something that is deemed valuable?",
        "What is the reverse of something that is highly esteemed?",
        "What is the opposite of something that is considered to be worthy?",
        "What is the antithesis of something that is valuable?",
        "What is the contrasting term for something that is esteemed?",
    ],
    [
        "In what locations are the majority of rosebushes typically found?",
        "What are the primary areas where rosebushes can be found?",
        "Where can nearly all rosebushes be located?",
        "What are the common habitats for rosebushes?",
        "In which regions are the majority of rosebushes located?",
        "What are the typical places to find rosebushes?",
        "Where are most rosebushes typically situated?",
        "What are the predominant areas for finding rosebushes?",
        "Where can one usually find the majority of rosebushes?",
        "In what types of environments are rosebushes usually found?",
    ],
    [
        "In times of injury, what are the desires of a person?",
        "What is the sought-after comfort for someone in pain?",
        "What are the needs of an individual who has been injured?",
        "When someone is hurt, what do they typically hope for?",
        "What are the wishes of an injured person?",
        "What are the expectations of a person when they are hurt?",
        "What do individuals seek when they are in pain?",
        "What are the longings of someone who has suffered an injury?",
        "What do people seek to fulfill when they are hurt?",
        "What are the desired outcomes for someone experiencing physical pain?",
    ],
    [
        "In what location could you find a small quantity of lint?",
        "Can you identify a place with a small amount of lint?",
        "Where is it likely to find a small amount of lint?",
        "Do you know where a small bit of lint might be found?",
        "In which area could you spot a small amount of lint?",
        "Is there a specific place where you might find a small amount of lint?",
        "Are you aware of any location that could have a small amount of lint?",
        "Can you point out a place where there might be a small bit of lint?",
        "Where in your home or workplace could you find a small amount of lint?",
        "Can you think of a spot where a small amount of lint might accumulate?",
    ],
    [
        "What are the skills and knowledge that a child gains from their education?",
        "What are the important lessons that children receive from their schooling?",
        "What is the purpose of a child's education in school?",
        "What are the key things that children are taught in school?",
        "What are the fundamental concepts and abilities that children develop through their education?",
        "What are the main objectives of a child's education in school?",
        "What are the essential teachings that children acquire during their schooling?",
        "What are the valuable experiences that children gain from their education?",
        "What are the crucial aspects of learning that children encounter in school?",
        "What are the key takeaways for children from their time in school?",
    ],
    [
        "What steps can be taken to get ready for a jog?",
        "How can one best prepare themselves before going for a run?",
        "What is necessary for a successful run preparation?",
        "How should one get ready before heading out for a run?",
        "What are the important things to do before going for a run?",
        "What steps should be taken to properly prepare for a run?",
        "What should you do to get yourself ready for a run?",
        "How can one effectively prepare themselves before a jog?",
        "What are the essential steps to take before going on a run?",
        "What are the key things to consider before starting a run?",
    ],
    [
        "What frequently occurs during conversations with friends?",
        "What is a common occurrence during chats with friends?",
        "What often takes place when chatting with friends?",
        "What happens frequently when conversing with friends?",
        "What is a regular happening when talking with friends?",
        "What is a usual event during chats with friends?",
        "What is a frequent outcome of chatting with friends?",
        "What is a common experience while talking with friends?",
        "What is a regular phenomenon during conversations with friends?",
        "What often occurs while chatting with friends?",
    ],
    [
        "What are some strategies for preventing boredom?",
        "What are some ways to keep oneself entertained and engaged?",
        "How can someone actively avoid feeling bored?",
        "What are some techniques for overcoming boredom?",
        "How can someone stay occupied and avoid getting bored?",
        "What are some tips for staying engaged and interested in activities?",
        "How can someone prevent themselves from becoming bored?",
        "What are some ways to keep one's mind stimulated and avoid boredom?",
        "How can someone fill their time to avoid feeling bored?",
        "What can someone do to stay entertained and avoid experiencing boredom?",
    ],
    [
        "What is the main location of a country's major industry?",
        "In what area are a country's major industries located?",
        "Where can you typically find the major industry of a country?",
        "What is the primary region for a country's major industry?",
        "Where are the majority of a country's major industries located?",
        "Where would you expect to find a country's main industry?",
        "What is the typical location for a country's major industry?",
        "In what region are most of a country's major industries concentrated?",
        "Where is the central hub of a country's major industry?",
        "What is the primary location for a country's major industry?",
    ],
    [
        "On which surface would you place your foot?",
        "Which area would you put your foot on?",
        "On what would you step with your foot?",
        "Where would you place your foot on a flat surface?",
        "On which specific section would you place your foot?",
        "Which specific spot would you apply your weight to?",
        "What kind of flooring would you step on?",
        "Where specifically would you position your foot on a hard surface?",
        "On which particular material would you apply pressure with your foot?",
        "In what location would you place your foot on a solid surface?",
    ],
    [
        "In what specific location do you plan to set up a security system?",
        "Which area of your property do you think is most suitable for a security system installation?",
        "What is the ideal location for placing a security system in your home or business?",
        "Where do you think it would be most effective to install a security system?",
        "In what part of your property do you believe a security system is most needed?",
        "Where are you considering installing a security system?",
        "Which areas of your property do you feel require a security system installation?",
        "What specific spots do you think would benefit from a security system installation?",
        "Where do you think a security system would serve its purpose best?",
        "In what specific area would you want to set up a security system for your property?",
    ],
    [
        "What is the object that supports a lit cigarette?",
        "What is the item that holds a lit cigarette in place?",
        "What is the device that contains a lit cigarette?",
        "What is the mechanism for holding a lit cigarette?",
        "What is the apparatus used to support a lit cigarette?",
        "What is the equipment that secures a lit cigarette in place?",
        "What is the tool that keeps a lit cigarette steady?",
        "What is the contraption for holding a lit cigarette while it burns?",
        "What is the instrument used to hold a lit cigarette?",
        "What is the device that keeps a lit cigarette from falling or being extinguished?",
    ],
    [
        "What are the locations where people come together to participate in athletics?",
        "What is the place where individuals meet to engage in physical activities and competitions?",
        "What spots do people congregate to partake in sports and games?",
        "Where can one find a gathering of people for sporting events?",
        "What are the venues where humans assemble for athletic competitions?",
        "What are the specific areas where people gather to play sports?",
        "What places do individuals convene to watch or participate in sports activities?",
        "What are the locations where humans come together for recreational and competitive sports?",
        "Where can one go to witness a group of people engaging in various sporting activities?",
        "What are the spaces where humans gather to enjoy sports and physical games?",
    ],
    [
        "What location has the strongest light source?",
        "What is the location of the most intense light source?",
        "Where can the most powerful light be found?",
        "What place has the greatest light source?",
        "What is the whereabouts of the most potent light source?",
        "Where can the most robust light source be located?",
        "What is the strongest source of light and where is it?",
        "Where is the greatest intensity of light found?",
        "What location is home to the most powerful light source?",
        "What is the location of the most dominant light source?",
    ],
    [
        "What are the motivations behind a person's decision to work?",
        "What do individuals hope to accomplish through employment?",
        "What goals do people seek to achieve through their professional endeavors?",
        "What drives a person to pursue a career?",
        "What do individuals aim to gain from their work?",
        "What is the purpose of a person's employment?",
        "What do people aspire to accomplish through their jobs?",
        "What are the desired outcomes of a person's work?",
        "What do individuals seek to fulfill by being employed?",
        "What do people hope to accomplish by working?",
    ],
    [
        "What are the initial steps in beginning the process of procreation?",
        "What is the first thing one should do when considering procreation?",
        "How does one initiate the process of creating offspring?",
        "What are the starting actions for procreating?",
        "What is the beginning point for the process of procreation?",
        "How does one kick off the procreation process?",
        "What are the first steps in starting the procreating process?",
        "What actions should one take to begin procreation?",
        "How does one commence the process of procreating?",
        "What is the first step in the procreation process?",
    ],
    [
        "What kind of chair includes a horizontal support bar?",
        "Which chair style features a crossbar at the base?",
        "What type of seating has an additional horizontal brace for support?",
        "Can you name a chair design with a rung included?",
        "What chair design incorporates a rung for added stability?",
        "Is there a specific term for a chair with a rung?",
        "Can you describe a chair with a rung in its structure?",
        "Which type of chair includes a horizontal bar for reinforcement?",
        "Do you know of any chair style that includes a rung across the base?",
        "Have you seen a chair with a rung before?",
    ],
    [
        "What qualities or characteristics are needed to successfully complete the class?",
        "What is required in order to pass the class?",
        "What kind of person is likely to pass the class?",
        "What are the necessary criteria for passing the class?",
        "What do you need to possess in order to pass the class?",
        "What is the key to passing the class?",
        "What attributes or traits are important in passing the class?",
        "What are the essential qualifications for passing the class?",
        "What is required from students to pass the class?",
        "What kind of students are likely to succeed in the class?",
    ],
    [
        "What are the potential consequences of prolonged kissing?",
        "How might extended kissing affect a person's health?",
        "What are the possible outcomes of kissing for an extended period of time?",
        "What could be the result of kissing for a long time?",
        "How can prolonged kissing impact someone's well-being?",
        "What are the potential risks of prolonged kissing?",
        "How might extended kissing influence a person's relationships?",
        "What are the potential effects of prolonged kissing on physical intimacy?",
        "How can kissing for a prolonged period impact a person's emotional state?",
        "What are the potential implications of prolonged kissing on a person's behavior?",
    ],
    [
        "In what locations can a horse roam freely?",
        "What are some places where a horse could roam about?",
        "Where could one find a horse freely wandering?",
        "What areas are suitable for a horse to wander around in?",
        "What are some possible places for a horse to wander?",
        "In which areas might a horse roam around?",
        "What are some potential locations for a horse to wander freely?",
        "Where could a horse be found roaming?",
        "What are some spots where a horse might wander about?",
        "In what places can one expect to find a wandering horse?",
    ],
    [
        "What methods are available for students to gain knowledge about marmots?",
        "What are the ways in which a student can educate themselves about marmots?",
        "In what ways can a student acquire information about marmots?",
        "What resources are accessible to students to learn about marmots?",
        "What are some effective ways for students to discover more about marmots?",
        "How can students go about learning about marmots?",
        "What are the steps that a student can take to become educated about marmots?",
        "What are the possible ways for a student to familiarize themselves with marmots?",
        "What are the available options for students to explore the world of marmots?",
        "What avenues are open to students for learning about marmots?",
    ],
    [
        "After completing their college education, what are the typical next steps for a student?",
        "What opportunities are available to a student after they finish college?",
        "What is the usual course of action for a college graduate in terms of their career?",
        "What are the options for a student once they have graduated from college?",
        "How might a student's path unfold after they graduate from college?",
        "What steps can a college graduate take to begin their professional journey?",
        "What are the common paths for a student to pursue after graduating college?",
        "What are the potential paths for a student to follow after completing their studies at college?",
        "How might a student's future unfold after they finish their college studies?",
        "What are the typical next steps for a student after they graduate from college?",
    ],
    [
        "In what way could someone be preparing to sell products or services?",
        "What are the possible methods for someone to enter the market?",
        "How might someone be planning to enter the marketplace?",
        "What are the various ways someone could be getting ready to sell their offerings?",
        "How could someone be approaching the market for their business?",
        "What are the different strategies someone might use to enter the market?",
        "In what ways can someone be getting prepared to sell in the market?",
        "What are the potential approaches someone might take to launch their products or services?",
        "How might someone be strategizing to enter the marketplace?",
        "What are the different avenues someone could be exploring to enter the market?",
    ],
    [
        "What are the typical benefits of exercise?",
        "What is exercise aimed at enhancing?",
        "What is the general goal of exercise?",
        "What does exercise usually strive to enhance?",
        "What improvements does exercise commonly aim to bring about?",
        "What are the usual targets of exercise?",
        "What areas does exercise commonly seek to improve?",
        "What does exercise generally seek to boost?",
        "What does exercise typically aim to cultivate?",
        "What does exercise usually aim to better?",
    ],
    [
        "In which country of south asia can a temple be found?",
        "What specific location in south asia is known for its temples?",
        "Is there a particular city in south asia that is famous for its temples?",
        "Where can one visit a temple in south asia?",
        "What are some notable temples located in south asia?",
        "Can you name a specific region in south asia where temples are prevalent?",
        "In which south asian country can one explore a variety of temples?",
        "Where exactly in south asia can one experience the beauty of ancient temples?",
        "Are there any famous religious sites in south asia known for their temples?",
        "What are some popular destinations in south asia for temple visits?",
    ],
    [
        "In what location do you create the pie?",
        "What is the setting for preparing the pie?",
        "At which place do you bake the pie?",
        "What is the specific area where you cook the pie?",
        "In what spot do you make the pie?",
        "Where exactly do you prepare the pie?",
        "At what venue do you cook the pie?",
        "What is the designated space for baking the pie?",
        "In what place do you typically cook the pie?",
        "What is the designated location for creating the pie?",
    ],
    [
        "What is the location of their performance?",
        "In what venue is their performance taking place?",
        "Where are they showcasing their performance?",
        "At which place can their performance be seen?",
        "What is the setting for their performance?",
        "Where is the stage for their performance located?",
        "At what place can their performance be viewed?",
        "What is the site of their performance?",
        "In what location can you witness their performance?",
        "Where will their performance be presented?",
    ],
    [
        "Where is it possible to obtain a product from a company?",
        "From which sources can you purchase items from a company?",
        "What are some ways that you can receive products from a company?",
        "In what ways can you acquire something from a company?",
        "Where can you find products that are made by a company?",
        "What are the different avenues for obtaining items from a company?",
        "Where can you access goods from a company?",
        "What are some locations where you can obtain products from a company?",
        "What are some methods for obtaining something from a company?",
        "Where can you purchase merchandise from a company?",
    ],
    [
        "What are the potential consequences of expressing yourself illegally?",
        "What kind of trouble could you get into for expressing yourself illegally?",
        "In what ways could expressing yourself illegally impact your life?",
        "What are the risks of illegally expressing your opinions?",
        "What would be the result of breaking the law while expressing yourself?",
        "What could happen if you engage in illegal self-expression?",
        "How could illegally expressing yourself affect your future opportunities?",
        "What are the possible legal repercussions of expressing yourself unlawfully?",
        "What would happen if you were to illegally express your thoughts or opinions?",
        "How might illegal self-expression impact your relationships and reputation?",
    ],
    [
        "What is a common surface that cats come into contact with on a daily basis?",
        "On a regular basis, where do cats tend to touch a surface?",
        "Where can you find a surface that cats typically interact with each day?",
        "What is a surface that cats frequently touch in their daily routines?",
        "In their daily activities, where do cats typically touch a surface?",
        "Where might a cat commonly come into contact with a surface each day?",
        "What is a surface that cats normally touch daily?",
        "Where can you find a surface that cats regularly come into contact with?",
        "What surface do cats usually touch on a daily basis?",
        "In their daily routines, where do cats often come into contact with a surface?",
    ],
    [
        "What is the behavior of a female flea after mating?",
        "How does a female flea behave after mating?",
        "What are the post-mating activities of a female flea?",
        "After mating, what are the actions of a female flea?",
        "What does a female flea typically do after mating?",
        "How does a female flea change its behavior after mating?",
        "What are the reproductive habits of a female flea after mating?",
        "What are the post-copulation behaviors of a female flea?",
        "What happens to a female flea after it has mated?",
        "What are the mating-related activities of a female flea?",
    ],
    [
        "In which location is it probable to find a checkout desk?",
        "What is the expected place for a checkout desk to be located?",
        "Where would you typically find a checkout desk situated?",
        "In what area is it common to see a checkout desk?",
        "What is the usual location for a checkout desk?",
        "Where is the anticipated place to find a checkout desk?",
        "In which spot is it likely to have a checkout desk?",
        "What is the standard place for a checkout desk to be found?",
        "Where is it expected for a checkout desk to be positioned?",
        "What location is probable for a checkout desk to be placed?",
    ],
    [
        "In what location is a cow prone to shedding tears?",
        "Where might a cow be inclined to weep?",
        "In what setting is a cow expected to express sadness through tears?",
        "On what occasion would a cow be likely to cry?",
        "Where could one find a cow tearful?",
        "In what environment is a cow prone to shedding tears?",
        "Where is it common for a cow to cry?",
        "In what location is a cow likely to show signs of distress through tears?",
        "Where would one expect to find a cow shedding tears?",
        "Under what circumstances would a cow be expected to cry?",
    ],
    [
        "In what location do individuals engage in playing baseball?",
        "At what place do individuals choose to play baseball?",
        "Where can one find people participating in baseball games?",
        "What is the specific location where baseball is commonly played?",
        "In which area do people typically enjoy playing baseball?",
        "Where do individuals usually engage in the sport of baseball?",
        "At what venue do people typically participate in baseball activities?",
        "What specific location serves as a common site for playing baseball?",
        "Where is the common place for people to partake in baseball games?",
        "What is the usual location for people to play baseball?",
    ],
    [
        "What type of food has a heart that is delicious to consume?",
        "Which kind of heart is considered tasty and edible?",
        "What has a tasty heart that is pleasant to eat?",
        "What food contains a heart that is delicious and enjoyable to consume?",
        "What kind of heart is considered good for eating?",
        "What has a good to eat heart?",
        "What type of food has an edible and appetizing heart?",
        "Which kind of heart is considered favorable for eating?",
        "What has a heart that is enjoyable and delectable to eat?",
        "What food contains a heart that is considered good for consumption?",
    ],
    [
        "What types of foods can be easily grabbed with a spoon?",
        "Are there any specific dishes that come to mind when thinking about using a spoon?",
        "Can you think of any ingredients that would be easy to scoop up with a spoon?",
        "How do you decide which foods are best to eat with a spoon?",
        "Are there any particular meals that you usually use a spoon for?",
        "What are some items that you could easily eat with a spoon?",
        "What types of foods do you think would be best suited for eating with a spoon?",
        "Are there any specific occasions where using a spoon is necessary for eating a certain dish?",
        "Is there a particular reason why you would choose to use a spoon instead of another utensil for eating?",
        "Can you think of any dishes that are traditionally eaten with a spoon?",
    ],
    [
        "What is the purpose of having air conditioning during the summer months?",
        "Is there a need for air conditioning during the summer season?",
        "What are the reasons for having air conditioning in the summertime?",
        "In what ways does air conditioning benefit people during the summer?",
        "What are the advantages of using air conditioning in the hot weather?",
        "Why is air conditioning necessary in the summer?",
        "How does air conditioning contribute to comfort during the summer?",
        "What are the practical reasons for using air conditioning in the summer?",
        "What are the main benefits of having air conditioning in the summer?",
        "How does air conditioning help to improve living conditions in the summer?",
    ],
    [
        "What steps should be taken prior to engaging in conversation?",
        "What are the necessary preparations one should make before speaking?",
        "What is the recommended course of action before initiating a dialogue?",
        "What can individuals do before they start communicating with others?",
        "What are some important things to consider before speaking with someone?",
        "What should be done as a precursor to speaking?",
        "What actions can be taken before engaging in a conversation?",
        "What are the appropriate steps to take before talking with others?",
        "What kind of preparation is required before initiating a discussion?",
        "What should individuals do to prepare themselves before speaking with someone else?",
    ],
    [
        "What is the location where individuals typically sit to pray in a chair?",
        "In what position do people typically sit in a chair when praying?",
        "What is the usual place for individuals to sit when they are praying in a chair?",
        "Where is the designated spot for people to sit and pray in a chair?",
        "What is the specific location for individuals to sit and pray in a chair?",
        "Where do individuals generally sit to pray when using a chair?",
        "What is the customary spot for people to sit in a chair and pray?",
        "What is the usual seating arrangement for individuals when praying in a chair?",
        "Where is the preferred seat for people to sit and pray while using a chair?",
        "What is the usual seating position for individuals when they are praying in a chair?",
    ],
]

if __name__ == "__main__":
    assert (
        len(UNRELATED_SIMILAR_QUESTIONS) == 100
    ), "There should be 100 lists of similar questions."
    for question_list in UNRELATED_SIMILAR_QUESTIONS:
        assert (
            len(question_list) == 10
        ), f"Each list should contain 10 questions. Found {len(question_list)} at {question_list} with index {UNRELATED_SIMILAR_QUESTIONS.index(question_list)}"
        for question in question_list:
            assert isinstance(
                question, str
            ), f"Each question should be a string. Found {question} in {question_list}"
            assert question.endswith(
                "?"
            ), f"Each question should end with a question mark. Found {question} in {question_list}"
            assert (
                question.count("?") == 1
            ), f"Each question should only have one question mark. Found {question} in {question_list}"